---
title: "Breast Cancer Royston Altman"
author: "Jose Tamez"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(survival)
library(FRESA.CAD)
source("~/GitHub/FRESA.CAD/R/RRPlot.R")


```

```{r}
gbsgdata <- gbsg
rownames(gbsgdata) <- gbsgdata$pid
gbsgdata$pid <- NULL

odata <-rotterdam
rownames(odata) <- odata$pid
odata$pid <- NULL
odata$rfstime <- odata$rtime
odata$status <- odata$recur
odata$rtime <- NULL
odata$recur <- NULL

odata <- odata[,colnames(odata) %in% colnames(gbsgdata)]
table(odata$size) 
odata$size <- 10*(odata$size=="<=20") + 35*(odata$size=="20-50") + 60*(odata$size==">50")
table(odata$size) 

data <- as.data.frame(model.matrix(Surv(rfstime,status)~.*age,odata))
#data <- as.data.frame(model.matrix(Surv(rfstime,status)~.,odata))

data$`(Intercept)` <- NULL
table(odata[rownames(data),"status"])

dataBrestCancerTrain <- cbind(time=odata[rownames(data),"rfstime"],status=odata[rownames(data),"status"],data)
table(dataBrestCancerTrain$status)
colnames(dataBrestCancerTrain) <-str_replace_all(colnames(dataBrestCancerTrain),":","_")
colnames(dataBrestCancerTrain) <-str_replace_all(colnames(dataBrestCancerTrain)," ","")
colnames(dataBrestCancerTrain) <-str_replace_all(colnames(dataBrestCancerTrain),"\\.","_")
colnames(dataBrestCancerTrain) <-str_replace_all(colnames(dataBrestCancerTrain),"-","_")
colnames(dataBrestCancerTrain) <-str_replace_all(colnames(dataBrestCancerTrain),">","_")
dataBrestCancerTrain$time <- dataBrestCancerTrain$time/365



colnames(gbsgdata)
gbsgdata <- gbsgdata[,colnames(odata)]
data <- as.data.frame(model.matrix(Surv(rfstime,status)~.*age,gbsgdata))
#data <- as.data.frame(model.matrix(Surv(rfstime,status)~.,gbsgdata))

data$`(Intercept)` <- NULL
table(odata[rownames(data),"status"])

dataBrestCancerTest <- cbind(time=gbsgdata[rownames(data),"rfstime"],status=gbsgdata[rownames(data),"status"],data)
table(gbsgdata$status)
colnames(dataBrestCancerTest) <-str_replace_all(colnames(dataBrestCancerTest),":","_")
colnames(dataBrestCancerTest) <-str_replace_all(colnames(dataBrestCancerTest)," ","")
colnames(dataBrestCancerTest) <-str_replace_all(colnames(dataBrestCancerTest),"\\.","_")
colnames(dataBrestCancerTest) <-str_replace_all(colnames(dataBrestCancerTest),"-","_")
colnames(dataBrestCancerTest) <-str_replace_all(colnames(dataBrestCancerTest),">","_")
dataBrestCancerTest$time <- dataBrestCancerTest$time/365



```

## Modeling
```{r}


ml <- BSWiMS.model(Surv(time,status)~.,data=dataBrestCancerTrain,loops=0,NumberofRepeats = 3)
#ml$bagging$bagged.model$formula.List

#dataBrestCancerR <- subset(dataBrestCancerTrain, time>=5*365 | status==1)
#dataBrestCancerR$status <- dataBrestCancerR$status * (dataBrestCancerR$time < 5*365)
#riskInterval <- median(subset(dataBrestCancerR,status==1)$time)/365
                

#dataBrestCancerR$time <- NULL
#table(dataBrestCancerTrain$status)
#table(dataBrestCancerR$status)
#ml <- BSWiMS.model(status~1,data=dataBrestCancerR,loops=20,NumberofRepeats = 10)

sm <- summary(ml)
pander::pander(sm$coefficients)
```

## Estimate h0 and Interval Time

```{r}


CalibrationProbPoissonRisk <- function(Riskdata)
### Risk data is a matrix of a Poisson event with Event, Probability of Event>0, and Time to Event]
{

  Riskdata <- as.data.frame(Riskdata)
  colnames(Riskdata) <- c("Event","pGZ","Time")
  observed <- sum(Riskdata$Event)
  meaninterval <- mean(Riskdata[Riskdata$Event==1,"Time"]);
  h0 <- 1.0/meaninterval
  index <- log(-log(1.0-Riskdata$pGZ)/h0)
  hazard <- h0*exp(index)
  probGZero <- 1.0-exp(-hazard)
  expected <- sum(probGZero)
  delta <- abs(observed-expected)/observed
  while (delta>0.005)
  {
    gain <- expected/observed
    h0 <- h0/gain
    hazard <- h0*exp(index)
    probGZero <- 1.0-exp(-hazard)
    expected <- sum(probGZero)
    delta <- abs(observed-expected)/observed
  }
  timeInterval <- 2.0*meaninterval
  timeSorted <- Riskdata
  timeSorted$hazard <- hazard
  timeSorted <- timeSorted[order(Riskdata$Time),]
  Ahazard <- 0
  for (idx in c(1:nrow(timeSorted)))
  {
    nevent <- timeSorted[idx,"hazard"]*timeSorted[idx,"Time"]/timeInterval
    if (nevent > 1.0) nevent <- 1.0
    Ahazard <- Ahazard + nevent
  }
  timeInterval <- timeInterval*Ahazard/observed
  Ahazard <- 0
  for (idx in c(1:nrow(timeSorted)))
  {
    nevent <- timeSorted[idx,"hazard"]*timeSorted[idx,"Time"]/timeInterval
    if (nevent > 1.0) nevent <- 1.0
    Ahazard <- Ahazard + nevent
  }
  
  result <- list(index=index,
                 probGZero=probGZero,
                 hazard=hazard,
                 h0=h0,
                 timeInterval = timeInterval,
                 meaninterval = meaninterval,
                 Ahazard=Ahazard,
                 delta=delta)
  return (result)
}

CoxRiskCalibration <- function(ml,data,outcome,time)
{
  index <- predict(ml,data)
  meaninterval <- mean(data[data[,outcome]==1,time]);
  h0 <- 1.0/meaninterval
  hazard <- h0*exp(index)
  probGZero <- 1.0-exp(-hazard)

  Riskdata <- cbind(data[,outcome],probGZero,data[,time])
  result <- CalibrationProbPoissonRisk(Riskdata)
  
  # observed <- sum(data[,outcome])
  # meaninterval <- mean(data[data[,outcome]==1,time]);
  # h0 <- 1.0/meaninterval
  # index <- predict(ml,data)
  # hazard <- h0*exp(index)
  # probGZero <- 1.0-exp(-hazard)
  # expected <- sum(probGZero)
  # delta <- abs(observed-expected)/observed
  # while (delta>0.005)
  # {
  #   gain <- expected/observed
  #   h0 <- h0/gain
  #   hazard <- h0*exp(index)
  #   probGZero <- 1.0-exp(-hazard)
  #   expected <- sum(probGZero)
  #   delta <- abs(observed-expected)/observed
  # }
  # timeInterval <- 2.0*meaninterval
  # timeSorted <- data
  # timeSorted$hazard <- hazard
  # timeSorted <- timeSorted[order(data[,time]),]
  # Ahazard <- 0
  # for (idx in c(1:nrow(timeSorted)))
  # {
  #   nevent <- timeSorted[idx,"hazard"]*timeSorted[idx,time]/timeInterval
  #   if (nevent > 1.0) nevent <- 1.0
  #   Ahazard <- Ahazard + nevent
  # }
  # timeInterval <- timeInterval*Ahazard/observed
  # Ahazard <- 0
  # for (idx in c(1:nrow(timeSorted)))
  # {
  #   nevent <- timeSorted[idx,"hazard"]*timeSorted[idx,time]/timeInterval
  #   if (nevent > 1.0) nevent <- 1.0
  #   Ahazard <- Ahazard + nevent
  # }
  # 
  # result <- list(index=index,
  #                probGZero=probGZero,
  #                hazard=hazard,
  #                h0=h0,
  #                timeInterval=timeInterval,
  #                meaninterval = meaninterval,
  #                Ahazard=Ahazard,
  #                delta=delta)
  return (result)
}




```

```{r}
op <- par(no.readonly = TRUE)

table(dataBrestCancerTrain$status)

calprob <- CoxRiskCalibration(ml,dataBrestCancerTrain,"status","time")

h0 <- calprob$h0
timeinterval <- calprob$timeInterval;
summary(calprob$prob)

rdata <- cbind(dataBrestCancerTrain$status,calprob$prob)


rrAnalysisTrain <- RRPlot(rdata,atProb=c(0.90,0.80),
                     timetoEvent=dataBrestCancerTrain$time,
                     title="Breast Cancer",
                     ysurvlim=c(0.00,1.0),
                     riskTimeInterval=timeinterval)



pre <- predict(ml,dataBrestCancerTest)
pp <- predictionStats_binary(cbind(dataBrestCancerTest$status,pre),plotname="Breast Cancer")


pre <- h0*exp(pre)
summary(pre)
prob <- (1.0-dpois(0,pre))
summary(prob)

par(op)
rdata <- cbind(dataBrestCancerTest$status,prob)
pp <- predictionStats_binary(rdata,plotname="Breast Cancer")
par(op)
rrAnalysis <- RRPlot(rdata,atThr=rrAnalysisTrain$thr_atP,
                     timetoEvent=dataBrestCancerTest$time,
                     title="Breast Cancer: Test",
                     ysurvlim=c(0.00,1.0),
                     riskTimeInterval=timeinterval)

par(op)


calprob <- CoxRiskCalibration(ml,dataBrestCancerTest,"status","time")

h0 <- calprob$h0
timeinterval <- calprob$timeInterval;
rdata <- cbind(dataBrestCancerTest$status,calprob$prob)

rrAnalysis <- RRPlot(rdata,atProb=c(0.90,0.80),
                     timetoEvent=dataBrestCancerTest$time,
                     title="Breast Cancer: Test",
                     ysurvlim=c(0.00,1.0),
                     riskTimeInterval=timeinterval)


```

