---
title: "Breast Cancer"
author: "Jose Tamez"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(survival)
library(FRESA.CAD)
source("~/GitHub/FRESA.CAD/R/RRPlot.R")


```

```{r}


dataBreast <- read.csv("~/GitHub/RISKPLOTS/DATA/wpbc.data", header=FALSE)

rownames(dataBreast) <- dataBreast$V1
dataBreast$V1 <- NULL
dataBreast$status <- 1*(dataBreast$V2=="R")
dataBreast$V2 <- NULL
dataBreast <- sapply(dataBreast,as.numeric)
dataBreast <- as.data.frame(dataBreast[complete.cases(dataBreast),])
class(dataBreast$V3)
class(dataBreast$V4)

```

## Modeling
```{r}
#ml <- BSWiMS.model(Surv(V3,status)~1,data=dataBreast,loops=0)

dtaRd <- dataBreast
dtaRd$V3 <- NULL
ml <- BSWiMS.model("status~.",data=dtaRd,NumberofRepeats = 10)

sm <- summary(ml)
pander::pander(sm$coefficients)
```

```{r}
op <- par(no.readonly = TRUE)

pre <- predict(ml,dataBreast,type="prob")
rdata <- cbind(dataBreast$status,pre)

#pp <- predictionStats_binary(rdata,plotname="Breast Cancer")
#par(op)

preval <- mean(dataBreast$status)
rrAnalysis1Y <- RRPlot(rdata,atProb=c(0.90),
                     timetoEvent=dataBreast$V3/365,
                     title="BCW",
                     ysurvlim=c(0.00,1.0),
                     riskTimeInterval=0.1)



```
