---
title: "free light chain"
author: "Jose Tamez"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(survival)
library(FRESA.CAD)
#library(corrplot)
source("~/GitHub/FRESA.CAD/R/RRPlot.R")


```

```{r}
odata <- flchain
odata$chapter <- NULL
table(odata$death)
rownames(odata) <- c(1:nrow(odata))
data <- as.data.frame(model.matrix(Surv(futime,death)~.,odata))

data$`(Intercept)` <- NULL
table(odata[rownames(data),"death"])

dataFL <- cbind(time=odata[rownames(data),"futime"],status=odata[rownames(data),"death"],data)
dataFL$time <- dataFL$time/365
table(dataFL$status)
colnames(dataFL) <-str_replace_all(colnames(dataFL)," ","")
colnames(dataFL) <-str_replace_all(colnames(dataFL),"\\.","_")

trainsamples <- sample(nrow(dataFL),2000)
dataFLTrain <- dataFL[trainsamples,]
dataFLTest <- dataFL[-trainsamples,]
```

## Modeling
```{r}
ml <- BSWiMS.model(Surv(time,status)~1,data=dataFLTrain,loops=0,NumberofRepeats = 1)
#dataFLR <- dataFLTrain
#dataFLR$time <- NULL
#ml <- BSWiMS.model(status~1,data=dataFLR,loops=0,NumberofRepeats = 1)

sm <- summary(ml)
pander::pander(sm$coefficients)
```

```{r}
op <- par(no.readonly = TRUE)

table(dataFLTrain$status)
times <- subset(dataFLTrain,status==1)$time
avgtime <- median(times)
lammda <- 1.0/avgtime
timeinterval <- 2.0*avgtime
rate <- sum(dataFLTrain$status)/nrow(dataFLTrain)
h0 <- 1.4*lammda
pre <- predict(ml,dataFLTrain)
summary(pre)
pre <- h0*exp(pre)
summary(pre)
prob <- (1.0-exp(-pre))
summary(prob)

rdata <- cbind(dataFLTrain$status,pre)
pp <- predictionStats_binary(rdata,plotname="free light chain")
par(op)

rdata <- cbind(dataFLTrain$status,prob)
rrAnalysis1Y <- RRPlot(rdata,atProb=c(0.90),
                     timetoEvent=dataFLTrain$time,
                     title="Serum: FLC",
                     ysurvlim=c(0.00,1.0),
                     riskTimeInterval=timeinterval)


pre <- predict(ml,dataFLTest)
pre <- h0*exp(pre)
prob <- (1.0-exp(-pre))

rdata <- cbind(dataFLTest$status,pre)
pp <- predictionStats_binary(rdata,plotname="free light chain")
par(op)

rdata <- cbind(dataFLTest$status,prob)
rrAnalysis1Y <- RRPlot(rdata,atProb=c(0.90),
                     timetoEvent=dataFLTest$time,
                     title="Serum: FLC",
                     ysurvlim=c(0.00,1.0),
                     riskTimeInterval=timeinterval)

```

