---
title: "Lung Cancer"
author: "Jose Tamez"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(survival)
library(FRESA.CAD)
#library(corrplot)
source("~/GitHub/FRESA.CAD/R/RRPlot.R")


```

```{r}


data <- model.frame(Surv(time,status)~.,lung,na.action=NULL)
data$inst <- NULL
data$`Surv(time, status)` <- NULL
dataLung <- cbind(time=lung$time,status=lung$status-1,data)
dataLung <- dataLung[complete.cases(dataLung),]
```

## Modeling
```{r}
#ml <- BSWiMS.model(Surv(time,status)~1,data=dataLung,loops=20,NumberofRepeats = 10)
dataLungR <- dataLung
dataLungR$time <- NULL
ml <- BSWiMS.model(status~1,data=dataLungR,loops=20,NumberofRepeats = 10)

sm <- summary(ml)
pander::pander(sm$coefficients)
```

```{r}
op <- par(no.readonly = TRUE)

pre <- predict(ml,dataLung,type="prob")
pp <- predictionStats_binary(cbind(dataLung$status,pre),plotname="LUNG")
par(op)

rdata <- cbind(dataLung$status,pre)
rrAnalysis1Y <- RRPlot(rdata,atProb=c(0.90),
                     timetoEvent=dataLung$time/365,
                     title="Lung",
                     ysurvlim=c(0.00,1.0),
                     riskTimeInterval=0.9)


```

