---
title: "Simulation"
author: "Jose Tamez"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Poisson Events

## Libraries
```{r}
library(survival)
library(FRESA.CAD)
#source("~/GitHub/FRESA.CAD/R/RRPlot.R")
#source("~/GitHub/FRESA.CAD/R/PoissonEventRiskCalibration.R")
op <- par(no.readonly = TRUE)
pander::panderOptions('digits', 3)
#pander::panderOptions('table.split.table', 400)
pander::panderOptions('keep.trailing.zeros',TRUE)
layout(matrix(1:1, nrow=1))

```
## Parameters and risk
```{r}
censoredProb <- 0.05
timeSpan <- 10
timeInterval = 0.1
InitialPopulatoin <- 1000
ContBetaRate_1 <- 0.5
ContBetaRate_2 <- 0.025
BinBetaRate_1 <- 1.0
BinBetaRate_2 <- 2.0
betaRates <- c(ContBetaRate_1,ContBetaRate_2,BinBetaRate_1,BinBetaRate_2)
BaselineHazard <- 0.02
ContVar_1 <- runif(InitialPopulatoin)
summary(ContVar_1)
ContVar_2 <- rnorm(InitialPopulatoin,50,10)
ContVar_2[ContVar_2 < 1] <- 1 
summary(ContVar_2)
BinVar_1 <- rbinom(InitialPopulatoin,1,0.3)
table(BinVar_1)
BinVar_2 <- rbinom(InitialPopulatoin,1,0.25)
table(BinVar_2)

dataFeatures <- as.matrix(cbind(ContVar_1,ContVar_2,BinVar_1,BinVar_2))
hazardRate <- as.numeric(BaselineHazard*(dataFeatures %*% betaRates))
summary(hazardRate)

```

### Getting the events and time to event

```{r}
aliveSet <- c(1:InitialPopulatoin)
eventSet <- numeric(InitialPopulatoin)
timetoEvent <- numeric(InitialPopulatoin)

for (time in c(1:(timeSpan/timeInterval)))
{
  randProb <- runif(length(aliveSet))
  Iscensored <- randProb <= censoredProb
  Isevent <- randProb <= (1.0-exp(-hazardRate[aliveSet]))
  Iscensored <- Iscensored & !Isevent
  eventSet[aliveSet] <- Isevent
  timetoEvent[aliveSet] <- time*timeInterval-timeInterval/2
  isCensoredOrEvent <- Iscensored | Isevent
  aliveSet <- aliveSet[!isCensoredOrEvent]
  cat(length(aliveSet),"(",sum(isCensoredOrEvent),",",sum(Isevent),",",sum(Iscensored),")\n")
}
timetoEvent[aliveSet] <- time*timeInterval + timeInterval/2
summary(timetoEvent)
table(eventSet)
pevent <- (1.0-exp(-hazardRate))
summary(pevent)
simulatedDataFrame <- as.data.frame(cbind(status=eventSet,time=timetoEvent,pevent=pevent,dataFeatures))

```

## RRplots()

```{r}

plotTimeInterval <- 10.0

hazard <- -log(1.0-simulatedDataFrame$pevent)
hboost <- plotTimeInterval/timeInterval
pvalue <- 1.0-exp(-hboost*hazard)


rdata <- cbind(simulatedDataFrame$status,pvalue)
summary(rdata[,2])
table(simulatedDataFrame$status)


RRAnalysisCI <- RRPlot(rdata,atRate=c(0.90,0.80),
                     timetoEvent=simulatedDataFrame$time,
                     title="Simulation",
                     ysurvlim=c(0.00,1.0),
                     riskTimeInterval=plotTimeInterval)

par(op)

```


### Risk Calibration

```{r results = "asis", warning = FALSE , dpi=300, fig.height= 5.0, fig.width= 7.0}
op <- par(no.readonly = TRUE)


crdata <- cbind(simulatedDataFrame$status,pvalue,simulatedDataFrame$time)

#calprob <- CalibrationProbPoissonRisk(crdata,timeInterval=plotTimeInterval)
calprob <- CalibrationProbPoissonRisk(crdata)


pander::pander(c(h0=calprob$h0,
                 Gain=calprob$hazardGain,
                 DeltaTime=calprob$timeInterval),
               caption="Cox Calibration Parameters")

```

### After Calibration
```{r}

h0 <- calprob$h0

caldata <- cbind(simulatedDataFrame$status,calprob$prob)


rrAnalysisTrain <- RRPlot(caldata,atRate=c(0.90,0.80),
                     timetoEvent=simulatedDataFrame$time,
                     title="Cal. Simulation",
                     ysurvlim=c(0.00,1.0),
                     riskTimeInterval=calprob$timeInterval)

```

